# Generated by Django 5.0.2 on 2024-02-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_password_key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
