# Generated by Django 5.0.2 on 2024-02-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_reset_password_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords_History',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
