# Generated by Django 5.0.2 on 2024-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwords_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords_history',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='passwords_history',
            field=models.ManyToManyField(to='users.passwords_history'),
        ),
    ]
