# Generated by Django 5.0.2 on 2024-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_passwords_history_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='passwords_history',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='salt',
        ),
        migrations.AddField(
            model_name='users',
            name='passwords',
            field=models.ManyToManyField(to='users.password'),
        ),
        migrations.DeleteModel(
            name='Passwords_History',
        ),
    ]
