# Generated by Django 5.0.2 on 2024-02-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
